// Code generated by MockGen. DO NOT EDIT.
// Source: api/income/interface.go

// Package mock_income is a generated GoMock package.
package mock_income

import (
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
	models "gitlab.odds.team/worklog/api.odds-worklog/models"
)

// MockRepository is a mock of Repository interface
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// AddIncome mocks base method
func (m *MockRepository) AddIncome(u *models.Income) error {
	ret := m.ctrl.Call(m, "AddIncome", u)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddIncome indicates an expected call of AddIncome
func (mr *MockRepositoryMockRecorder) AddIncome(u interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddIncome", reflect.TypeOf((*MockRepository)(nil).AddIncome), u)
}

// GetIncomeUserByYearMonth mocks base method
func (m *MockRepository) GetIncomeUserByYearMonth(id string, fromYear int, fromMonth time.Month) (*models.Income, error) {
	ret := m.ctrl.Call(m, "GetIncomeUserByYearMonth", id, fromYear, fromMonth)
	ret0, _ := ret[0].(*models.Income)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetIncomeUserByYearMonth indicates an expected call of GetIncomeUserByYearMonth
func (mr *MockRepositoryMockRecorder) GetIncomeUserByYearMonth(id, fromYear, fromMonth interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIncomeUserByYearMonth", reflect.TypeOf((*MockRepository)(nil).GetIncomeUserByYearMonth), id, fromYear, fromMonth)
}

// GetIncomeByID mocks base method
func (m *MockRepository) GetIncomeByID(incID, uID string) (*models.Income, error) {
	ret := m.ctrl.Call(m, "GetIncomeByID", incID, uID)
	ret0, _ := ret[0].(*models.Income)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetIncomeByID indicates an expected call of GetIncomeByID
func (mr *MockRepositoryMockRecorder) GetIncomeByID(incID, uID interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIncomeByID", reflect.TypeOf((*MockRepository)(nil).GetIncomeByID), incID, uID)
}

// UpdateIncome mocks base method
func (m *MockRepository) UpdateIncome(income *models.Income) error {
	ret := m.ctrl.Call(m, "UpdateIncome", income)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateIncome indicates an expected call of UpdateIncome
func (mr *MockRepositoryMockRecorder) UpdateIncome(income interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateIncome", reflect.TypeOf((*MockRepository)(nil).UpdateIncome), income)
}

// AddExport mocks base method
func (m *MockRepository) AddExport(ep *models.Export) error {
	ret := m.ctrl.Call(m, "AddExport", ep)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddExport indicates an expected call of AddExport
func (mr *MockRepositoryMockRecorder) AddExport(ep interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddExport", reflect.TypeOf((*MockRepository)(nil).AddExport), ep)
}

// DropIncome mocks base method
func (m *MockRepository) DropIncome() error {
	ret := m.ctrl.Call(m, "DropIncome")
	ret0, _ := ret[0].(error)
	return ret0
}

// DropIncome indicates an expected call of DropIncome
func (mr *MockRepositoryMockRecorder) DropIncome() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DropIncome", reflect.TypeOf((*MockRepository)(nil).DropIncome))
}

// MockUsecase is a mock of Usecase interface
type MockUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockUsecaseMockRecorder
}

// MockUsecaseMockRecorder is the mock recorder for MockUsecase
type MockUsecaseMockRecorder struct {
	mock *MockUsecase
}

// NewMockUsecase creates a new mock instance
func NewMockUsecase(ctrl *gomock.Controller) *MockUsecase {
	mock := &MockUsecase{ctrl: ctrl}
	mock.recorder = &MockUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockUsecase) EXPECT() *MockUsecaseMockRecorder {
	return m.recorder
}

// AddIncome mocks base method
func (m *MockUsecase) AddIncome(req *models.IncomeReq, user *models.User) (*models.Income, error) {
	ret := m.ctrl.Call(m, "AddIncome", req, user)
	ret0, _ := ret[0].(*models.Income)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddIncome indicates an expected call of AddIncome
func (mr *MockUsecaseMockRecorder) AddIncome(req, user interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddIncome", reflect.TypeOf((*MockUsecase)(nil).AddIncome), req, user)
}

// UpdateIncome mocks base method
func (m *MockUsecase) UpdateIncome(id string, req *models.IncomeReq, user *models.User) (*models.Income, error) {
	ret := m.ctrl.Call(m, "UpdateIncome", id, req, user)
	ret0, _ := ret[0].(*models.Income)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateIncome indicates an expected call of UpdateIncome
func (mr *MockUsecaseMockRecorder) UpdateIncome(id, req, user interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateIncome", reflect.TypeOf((*MockUsecase)(nil).UpdateIncome), id, req, user)
}

// GetIncomeStatusList mocks base method
func (m *MockUsecase) GetIncomeStatusList(corporateFlag string) ([]*models.IncomeStatus, error) {
	ret := m.ctrl.Call(m, "GetIncomeStatusList", corporateFlag)
	ret0, _ := ret[0].([]*models.IncomeStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetIncomeStatusList indicates an expected call of GetIncomeStatusList
func (mr *MockUsecaseMockRecorder) GetIncomeStatusList(corporateFlag interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIncomeStatusList", reflect.TypeOf((*MockUsecase)(nil).GetIncomeStatusList), corporateFlag)
}

// GetIncomeByUserIdAndCurrentMonth mocks base method
func (m *MockUsecase) GetIncomeByUserIdAndCurrentMonth(userID string) (*models.Income, error) {
	ret := m.ctrl.Call(m, "GetIncomeByUserIdAndCurrentMonth", userID)
	ret0, _ := ret[0].(*models.Income)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetIncomeByUserIdAndCurrentMonth indicates an expected call of GetIncomeByUserIdAndCurrentMonth
func (mr *MockUsecaseMockRecorder) GetIncomeByUserIdAndCurrentMonth(userID interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIncomeByUserIdAndCurrentMonth", reflect.TypeOf((*MockUsecase)(nil).GetIncomeByUserIdAndCurrentMonth), userID)
}

// ExportIncome mocks base method
func (m *MockUsecase) ExportIncome(corporateFlag string) (string, error) {
	ret := m.ctrl.Call(m, "ExportIncome", corporateFlag)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExportIncome indicates an expected call of ExportIncome
func (mr *MockUsecaseMockRecorder) ExportIncome(corporateFlag interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExportIncome", reflect.TypeOf((*MockUsecase)(nil).ExportIncome), corporateFlag)
}

// Export Pdf mocks base method
func (m *MockUsecase) ExportPdf() (string, error) {
	ret := m.ctrl.Call(m, "ExportPdf")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Export Pdf an expected call of Export Pdf
func (mr *MockUsecaseMockRecorder) ExportPdf() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExportPdf", reflect.TypeOf((*MockUsecase)(nil).ExportPdf))
}

// DropIncome mocks base method
func (m *MockUsecase) DropIncome() error {
	ret := m.ctrl.Call(m, "DropIncome")
	ret0, _ := ret[0].(error)
	return ret0
}

// DropIncome indicates an expected call of DropIncome
func (mr *MockUsecaseMockRecorder) DropIncome() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DropIncome", reflect.TypeOf((*MockUsecase)(nil).DropIncome))
}
