// Code generated by MockGen. DO NOT EDIT.
// Source: gitlab.odds.team/worklog/api.odds-worklog/business/usecases (interfaces: ForViewingSAPExportFailures)

// Package sap_export_failure_mock is a generated GoMock package.
package sap_export_failure_mock

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	models "gitlab.odds.team/worklog/api.odds-worklog/business/models"
)

// MockForViewingSAPExportFailures is a mock of ForViewingSAPExportFailures interface.
type MockForViewingSAPExportFailures struct {
	ctrl     *gomock.Controller
	recorder *MockForViewingSAPExportFailuresMockRecorder
}

// MockForViewingSAPExportFailuresMockRecorder is the mock recorder for MockForViewingSAPExportFailures.
type MockForViewingSAPExportFailuresMockRecorder struct {
	mock *MockForViewingSAPExportFailures
}

// NewMockForViewingSAPExportFailures creates a new mock instance.
func NewMockForViewingSAPExportFailures(ctrl *gomock.Controller) *MockForViewingSAPExportFailures {
	mock := &MockForViewingSAPExportFailures{ctrl: ctrl}
	mock.recorder = &MockForViewingSAPExportFailuresMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockForViewingSAPExportFailures) EXPECT() *MockForViewingSAPExportFailuresMockRecorder {
	return m.recorder
}

// List mocks base method.
func (m *MockForViewingSAPExportFailures) List(arg0 int) ([]*models.SAPExportFailureLog, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", arg0)
	ret0, _ := ret[0].([]*models.SAPExportFailureLog)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockForViewingSAPExportFailuresMockRecorder) List(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockForViewingSAPExportFailures)(nil).List), arg0)
}
