workflow:
  rules:
    - if: '$CI_COMMIT_BRANCH == "develop"'
    - when: never

stages:
  - prepare
  - test
  - build
  - deploy

variables:
  AWS_DEFAULT_REGION: "ap-southeast-1"
  ECR_REGISTRY: "844772501268.dkr.ecr.ap-southeast-1.amazonaws.com"
  IMAGE_NAME: "api-worklog"
  IMAGE_TAG: "dev-odds-cloud"
  FULL_IMAGE_NAME: "$ECR_REGISTRY/$IMAGE_NAME:$IMAGE_TAG"
  SONAR_SCANNER_VERSION: "6.2.1.4610"
  GOMODCACHE: $CI_PROJECT_DIR/.cache/go-mod
  GOCACHE: $CI_PROJECT_DIR/.cache/go-build

cache:
  key:
    files:
      - go.mod
      - go.sum
  paths:
    - $GOMODCACHE

  prepare:
    stage: prepare
    image: cacher.odds.team/docker-hub-cache/golang:1.25.1

    script:
      - go env
      - go mod download

test:
  stage: test
  image: cacher.odds.team/docker-hub-cache/golang:1.25.1
  before_script:
    - mkdir -p coverage
  script:
    - go test -v -race -coverprofile=coverage/cover.out -covermode=atomic ./...
    - go get github.com/boumenot/gocover-cobertura
    - go run github.com/boumenot/gocover-cobertura < coverage/cover.out > coverage/coverage.xml
  artifacts:
    paths:
      - coverage
    expire_in: 1 hour
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage/cover.xml
  coverage: "/coverage: \\d+.\\d+% of statements/"

build:
  stage: build
  image: docker:27
  services:
    - name: docker:27-dind
  rules:
    - if: '$CI_COMMIT_BRANCH == "develop"'
  needs:
    - job: test
  variables:
    DOCKER_HOST: "tcp://docker:2375"
    DOCKER_TLS_CERTDIR: ""
  before_script:
    - apk add --no-cache aws-cli
    - aws ecr get-login-password --region "$AWS_DEFAULT_REGION" | docker login --username AWS --password-stdin "$ECR_REGISTRY"
  script:
    - docker build -t "$FULL_IMAGE_NAME" .
    - docker push "$FULL_IMAGE_NAME"

deploy:
  stage: deploy
  image: docker:27
  tags:
    - self-hosted
  rules:
    - if: '$CI_COMMIT_BRANCH == "develop"'
  needs:
    - job: build
  before_script:
    - apk add --no-cache aws-cli openssh-client
    - aws ecr get-login-password --region "$AWS_DEFAULT_REGION" | docker login --username AWS --password-stdin "$ECR_REGISTRY"
    - eval "$(ssh-agent -s)"
    - echo "$ODDS_CLOUD_DEV_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan -H "$ODDS_CLOUD_DEV_HOST" >> ~/.ssh/known_hosts
  script:
    - docker pull "$FULL_IMAGE_NAME"
    - scp "deployment/dev/docker-compose.yaml" "ubuntu@${ODDS_CLOUD_DEV_HOST}:/home/ubuntu/worklog/docker-compose.yaml"
    - ssh "ubuntu@${ODDS_CLOUD_DEV_HOST}" 'cd /home/ubuntu/worklog && docker compose pull && docker compose down && docker compose up -d'
