// Code generated by MockGen. DO NOT EDIT.
// Source: usecases/add_income_adaptors.go

// Package mock_usecases is a generated GoMock package.
package mock_usecases

import (
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
	models "gitlab.odds.team/worklog/api.odds-worklog/business/models"
)

// MockForControllingUserIncome is a mock of ForControllingUserIncome interface.
type MockForControllingUserIncome struct {
	ctrl     *gomock.Controller
	recorder *MockForControllingUserIncomeMockRecorder
}

// MockForControllingUserIncomeMockRecorder is the mock recorder for MockForControllingUserIncome.
type MockForControllingUserIncomeMockRecorder struct {
	mock *MockForControllingUserIncome
}

// NewMockForControllingUserIncome creates a new mock instance.
func NewMockForControllingUserIncome(ctrl *gomock.Controller) *MockForControllingUserIncome {
	mock := &MockForControllingUserIncome{ctrl: ctrl}
	mock.recorder = &MockForControllingUserIncomeMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockForControllingUserIncome) EXPECT() *MockForControllingUserIncomeMockRecorder {
	return m.recorder
}

// AddIncome mocks base method.
func (m *MockForControllingUserIncome) AddIncome(u *models.Income) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddIncome", u)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddIncome indicates an expected call of AddIncome.
func (mr *MockForControllingUserIncomeMockRecorder) AddIncome(u interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddIncome", reflect.TypeOf((*MockForControllingUserIncome)(nil).AddIncome), u)
}

// GetIncomeUserByYearMonth mocks base method.
func (m *MockForControllingUserIncome) GetIncomeUserByYearMonth(id string, fromYear int, fromMonth time.Month) (*models.Income, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIncomeUserByYearMonth", id, fromYear, fromMonth)
	ret0, _ := ret[0].(*models.Income)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetIncomeUserByYearMonth indicates an expected call of GetIncomeUserByYearMonth.
func (mr *MockForControllingUserIncomeMockRecorder) GetIncomeUserByYearMonth(id, fromYear, fromMonth interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIncomeUserByYearMonth", reflect.TypeOf((*MockForControllingUserIncome)(nil).GetIncomeUserByYearMonth), id, fromYear, fromMonth)
}

// MockForGettingUserByID is a mock of ForGettingUserByID interface.
type MockForGettingUserByID struct {
	ctrl     *gomock.Controller
	recorder *MockForGettingUserByIDMockRecorder
}

// MockForGettingUserByIDMockRecorder is the mock recorder for MockForGettingUserByID.
type MockForGettingUserByIDMockRecorder struct {
	mock *MockForGettingUserByID
}

// NewMockForGettingUserByID creates a new mock instance.
func NewMockForGettingUserByID(ctrl *gomock.Controller) *MockForGettingUserByID {
	mock := &MockForGettingUserByID{ctrl: ctrl}
	mock.recorder = &MockForGettingUserByIDMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockForGettingUserByID) EXPECT() *MockForGettingUserByIDMockRecorder {
	return m.recorder
}

// GetByID mocks base method.
func (m *MockForGettingUserByID) GetByID(id string) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", id)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockForGettingUserByIDMockRecorder) GetByID(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockForGettingUserByID)(nil).GetByID), id)
}
