// Code generated by MockGen. DO NOT EDIT.
// Source: business/usecases/export_income_from_timesheet_driven_ports.go

// Package mock_usecases is a generated GoMock package.
package mock_usecases

import (
	gomock "github.com/golang/mock/gomock"
	models "gitlab.odds.team/worklog/api.odds-worklog/business/models"
	reflect "reflect"
	time "time"
)

// MockForGettingIncomeFromTimesheetInTheMonth is a mock of ForGettingIncomeFromTimesheetInTheMonth interface
type MockForGettingIncomeFromTimesheetInTheMonth struct {
	ctrl     *gomock.Controller
	recorder *MockForGettingIncomeFromTimesheetInTheMonthMockRecorder
}

// MockForGettingIncomeFromTimesheetInTheMonthMockRecorder is the mock recorder for MockForGettingIncomeFromTimesheetInTheMonth
type MockForGettingIncomeFromTimesheetInTheMonthMockRecorder struct {
	mock *MockForGettingIncomeFromTimesheetInTheMonth
}

// NewMockForGettingIncomeFromTimesheetInTheMonth creates a new mock instance
func NewMockForGettingIncomeFromTimesheetInTheMonth(ctrl *gomock.Controller) *MockForGettingIncomeFromTimesheetInTheMonth {
	mock := &MockForGettingIncomeFromTimesheetInTheMonth{ctrl: ctrl}
	mock.recorder = &MockForGettingIncomeFromTimesheetInTheMonthMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockForGettingIncomeFromTimesheetInTheMonth) EXPECT() *MockForGettingIncomeFromTimesheetInTheMonthMockRecorder {
	return m.recorder
}

// GetAllByRoleStartDateAndEndDate mocks base method
func (m *MockForGettingIncomeFromTimesheetInTheMonth) GetAllByRoleStartDateAndEndDate(role string, startDate, endDate time.Time) ([]*models.IncomeFromTimesheet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllByRoleStartDateAndEndDate", role, startDate, endDate)
	ret0, _ := ret[0].([]*models.IncomeFromTimesheet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllByRoleStartDateAndEndDate indicates an expected call of GetAllByRoleStartDateAndEndDate
func (mr *MockForGettingIncomeFromTimesheetInTheMonthMockRecorder) GetAllByRoleStartDateAndEndDate(role, startDate, endDate interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllByRoleStartDateAndEndDate", reflect.TypeOf((*MockForGettingIncomeFromTimesheetInTheMonth)(nil).GetAllByRoleStartDateAndEndDate), role, startDate, endDate)
}
