// Code generated by MockGen. DO NOT EDIT.
// Source: usecases/get_income_adaptors.go

// Package mock_usecases is a generated GoMock package.
package mock_usecases

import (
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
	models "gitlab.odds.team/worklog/api.odds-worklog/business/models"
)

// MockForReadingUserIncome is a mock of ForReadingUserIncome interface.
type MockForReadingUserIncome struct {
	ctrl     *gomock.Controller
	recorder *MockForReadingUserIncomeMockRecorder
}

// MockForReadingUserIncomeMockRecorder is the mock recorder for MockForReadingUserIncome.
type MockForReadingUserIncomeMockRecorder struct {
	mock *MockForReadingUserIncome
}

// NewMockForReadingUserIncome creates a new mock instance.
func NewMockForReadingUserIncome(ctrl *gomock.Controller) *MockForReadingUserIncome {
	mock := &MockForReadingUserIncome{ctrl: ctrl}
	mock.recorder = &MockForReadingUserIncomeMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockForReadingUserIncome) EXPECT() *MockForReadingUserIncomeMockRecorder {
	return m.recorder
}

// GetIncomeByUserIdAllMonth mocks base method.
func (m *MockForReadingUserIncome) GetIncomeByUserIdAllMonth(userId string) ([]*models.Income, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIncomeByUserIdAllMonth", userId)
	ret0, _ := ret[0].([]*models.Income)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetIncomeByUserIdAllMonth indicates an expected call of GetIncomeByUserIdAllMonth.
func (mr *MockForReadingUserIncomeMockRecorder) GetIncomeByUserIdAllMonth(userId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIncomeByUserIdAllMonth", reflect.TypeOf((*MockForReadingUserIncome)(nil).GetIncomeByUserIdAllMonth), userId)
}

// GetIncomeUserByYearMonth mocks base method.
func (m *MockForReadingUserIncome) GetIncomeUserByYearMonth(id string, fromYear int, fromMonth time.Month) (*models.Income, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIncomeUserByYearMonth", id, fromYear, fromMonth)
	ret0, _ := ret[0].(*models.Income)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetIncomeUserByYearMonth indicates an expected call of GetIncomeUserByYearMonth.
func (mr *MockForReadingUserIncomeMockRecorder) GetIncomeUserByYearMonth(id, fromYear, fromMonth interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIncomeUserByYearMonth", reflect.TypeOf((*MockForReadingUserIncome)(nil).GetIncomeUserByYearMonth), id, fromYear, fromMonth)
}

// MockForUsingGetIncome is a mock of ForUsingGetIncome interface.
type MockForUsingGetIncome struct {
	ctrl     *gomock.Controller
	recorder *MockForUsingGetIncomeMockRecorder
}

// MockForUsingGetIncomeMockRecorder is the mock recorder for MockForUsingGetIncome.
type MockForUsingGetIncomeMockRecorder struct {
	mock *MockForUsingGetIncome
}

// NewMockForUsingGetIncome creates a new mock instance.
func NewMockForUsingGetIncome(ctrl *gomock.Controller) *MockForUsingGetIncome {
	mock := &MockForUsingGetIncome{ctrl: ctrl}
	mock.recorder = &MockForUsingGetIncomeMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockForUsingGetIncome) EXPECT() *MockForUsingGetIncomeMockRecorder {
	return m.recorder
}

// GetIncomeByCurrentMonth mocks base method.
func (m *MockForUsingGetIncome) GetIncomeByCurrentMonth(userId string) (*models.Income, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIncomeByCurrentMonth", userId)
	ret0, _ := ret[0].(*models.Income)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetIncomeByCurrentMonth indicates an expected call of GetIncomeByCurrentMonth.
func (mr *MockForUsingGetIncomeMockRecorder) GetIncomeByCurrentMonth(userId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIncomeByCurrentMonth", reflect.TypeOf((*MockForUsingGetIncome)(nil).GetIncomeByCurrentMonth), userId)
}

// GetIncomeByAllMonth mocks base method.
func (m *MockForUsingGetIncome) GetIncomeByAllMonth(userId string) ([]*models.Income, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIncomeByAllMonth", userId)
	ret0, _ := ret[0].([]*models.Income)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetIncomeByAllMonth indicates an expected call of GetIncomeByAllMonth.
func (mr *MockForUsingGetIncomeMockRecorder) GetIncomeByAllMonth(userId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIncomeByAllMonth", reflect.TypeOf((*MockForUsingGetIncome)(nil).GetIncomeByAllMonth), userId)
}
