// Code generated by MockGen. DO NOT EDIT.
// Source: business/usecases/get_income_from_timesheet_source_ports.go

// Package mock_usecases is a generated GoMock package.
package mock_usecases

import (
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
	models "gitlab.odds.team/worklog/api.odds-worklog/business/models"
)

// MockForReadingIncomeFromTimesheetByUser is a mock of ForReadingIncomeFromTimesheetByUser interface
type MockForReadingIncomeFromTimesheetByUser struct {
	ctrl     *gomock.Controller
	recorder *MockForReadingIncomeFromTimesheetByUserMockRecorder
}

// MockForReadingIncomeFromTimesheetByUserMockRecorder is the mock recorder for MockForReadingIncomeFromTimesheetByUser
type MockForReadingIncomeFromTimesheetByUserMockRecorder struct {
	mock *MockForReadingIncomeFromTimesheetByUser
}

// NewMockForReadingIncomeFromTimesheetByUser creates a new mock instance
func NewMockForReadingIncomeFromTimesheetByUser(ctrl *gomock.Controller) *MockForReadingIncomeFromTimesheetByUser {
	mock := &MockForReadingIncomeFromTimesheetByUser{ctrl: ctrl}
	mock.recorder = &MockForReadingIncomeFromTimesheetByUserMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockForReadingIncomeFromTimesheetByUser) EXPECT() *MockForReadingIncomeFromTimesheetByUserMockRecorder {
	return m.recorder
}

// GetByUserYearMonth mocks base method
func (m *MockForReadingIncomeFromTimesheetByUser) GetByUserYearMonth(userID string, year int, month time.Month) (*models.IncomeFromTimesheet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUserYearMonth", userID, year, month)
	ret0, _ := ret[0].(*models.IncomeFromTimesheet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUserYearMonth indicates an expected call of GetByUserYearMonth
func (mr *MockForReadingIncomeFromTimesheetByUserMockRecorder) GetByUserYearMonth(userID, year, month interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUserYearMonth", reflect.TypeOf((*MockForReadingIncomeFromTimesheetByUser)(nil).GetByUserYearMonth), userID, year, month)
}

// GetByUserIdAllMonth mocks base method
func (m *MockForReadingIncomeFromTimesheetByUser) GetByUserIdAllMonth(userId string) ([]*models.IncomeFromTimesheet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUserIdAllMonth", userId)
	ret0, _ := ret[0].([]*models.IncomeFromTimesheet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUserIdAllMonth indicates an expected call of GetByUserIdAllMonth
func (mr *MockForReadingIncomeFromTimesheetByUserMockRecorder) GetByUserIdAllMonth(userId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUserIdAllMonth", reflect.TypeOf((*MockForReadingIncomeFromTimesheetByUser)(nil).GetByUserIdAllMonth), userId)
}
