// Code generated by MockGen. DO NOT EDIT.
// Source: business/usecases/list_income_status_driving_ports.go

// Package mock_usecases is a generated GoMock package.
package mock_usecases

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	models "gitlab.odds.team/worklog/api.odds-worklog/business/models"
)

// MockForUsingListIncomeStatus is a mock of ForUsingListIncomeStatus interface.
type MockForUsingListIncomeStatus struct {
	ctrl     *gomock.Controller
	recorder *MockForUsingListIncomeStatusMockRecorder
}

// MockForUsingListIncomeStatusMockRecorder is the mock recorder for MockForUsingListIncomeStatus.
type MockForUsingListIncomeStatusMockRecorder struct {
	mock *MockForUsingListIncomeStatus
}

// NewMockForUsingListIncomeStatus creates a new mock instance.
func NewMockForUsingListIncomeStatus(ctrl *gomock.Controller) *MockForUsingListIncomeStatus {
	mock := &MockForUsingListIncomeStatus{ctrl: ctrl}
	mock.recorder = &MockForUsingListIncomeStatusMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockForUsingListIncomeStatus) EXPECT() *MockForUsingListIncomeStatusMockRecorder {
	return m.recorder
}

// GetIncomeStatusList mocks base method.
func (m *MockForUsingListIncomeStatus) GetIncomeStatusList(role string, isAdmin bool) ([]*models.IncomeStatus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIncomeStatusList", role, isAdmin)
	ret0, _ := ret[0].([]*models.IncomeStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetIncomeStatusList indicates an expected call of GetIncomeStatusList.
func (mr *MockForUsingListIncomeStatusMockRecorder) GetIncomeStatusList(role, isAdmin interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIncomeStatusList", reflect.TypeOf((*MockForUsingListIncomeStatus)(nil).GetIncomeStatusList), role, isAdmin)
}
