// Code generated by MockGen. DO NOT EDIT.
// Source: gitlab.odds.team/worklog/api.odds-worklog/business/usecases (interfaces: ForListingSAPExportFailures)

// Package mock_usecases is a generated GoMock package.
package mock_usecases

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	models "gitlab.odds.team/worklog/api.odds-worklog/business/models"
)

// MockForListingSAPExportFailures is a mock of ForListingSAPExportFailures interface.
type MockForListingSAPExportFailures struct {
	ctrl     *gomock.Controller
	recorder *MockForListingSAPExportFailuresMockRecorder
}

// MockForListingSAPExportFailuresMockRecorder is the mock recorder for MockForListingSAPExportFailures.
type MockForListingSAPExportFailuresMockRecorder struct {
	mock *MockForListingSAPExportFailures
}

// NewMockForListingSAPExportFailures creates a new mock instance.
func NewMockForListingSAPExportFailures(ctrl *gomock.Controller) *MockForListingSAPExportFailures {
	mock := &MockForListingSAPExportFailures{ctrl: ctrl}
	mock.recorder = &MockForListingSAPExportFailuresMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockForListingSAPExportFailures) EXPECT() *MockForListingSAPExportFailuresMockRecorder {
	return m.recorder
}

// List mocks base method.
func (m *MockForListingSAPExportFailures) List(arg0 int) ([]*models.SAPExportFailureLog, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", arg0)
	ret0, _ := ret[0].([]*models.SAPExportFailureLog)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockForListingSAPExportFailuresMockRecorder) List(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockForListingSAPExportFailures)(nil).List), arg0)
}
