// Code generated by MockGen. DO NOT EDIT.
// Source: gitlab.odds.team/worklog/api.odds-worklog/business/usecases (interfaces: ForListingTimesheetEventLogs)

// Package mock_usecases is a generated GoMock package.
package mock_usecases

import (
	gomock "github.com/golang/mock/gomock"
	models "gitlab.odds.team/worklog/api.odds-worklog/business/models"
	reflect "reflect"
)

// MockForListingTimesheetEventLogs is a mock of ForListingTimesheetEventLogs interface
type MockForListingTimesheetEventLogs struct {
	ctrl     *gomock.Controller
	recorder *MockForListingTimesheetEventLogsMockRecorder
}

// MockForListingTimesheetEventLogsMockRecorder is the mock recorder for MockForListingTimesheetEventLogs
type MockForListingTimesheetEventLogsMockRecorder struct {
	mock *MockForListingTimesheetEventLogs
}

// NewMockForListingTimesheetEventLogs creates a new mock instance
func NewMockForListingTimesheetEventLogs(ctrl *gomock.Controller) *MockForListingTimesheetEventLogs {
	mock := &MockForListingTimesheetEventLogs{ctrl: ctrl}
	mock.recorder = &MockForListingTimesheetEventLogsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockForListingTimesheetEventLogs) EXPECT() *MockForListingTimesheetEventLogsMockRecorder {
	return m.recorder
}

// List mocks base method
func (m *MockForListingTimesheetEventLogs) List(arg0 int) ([]*models.TimesheetEventLog, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", arg0)
	ret0, _ := ret[0].([]*models.TimesheetEventLog)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List
func (mr *MockForListingTimesheetEventLogsMockRecorder) List(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockForListingTimesheetEventLogs)(nil).List), arg0)
}
