// Code generated by MockGen. DO NOT EDIT.
// Source: business/usecases/list_income_status_driven_ports.go

// Package mock_usecases is a generated GoMock package.
package mock_usecases

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	models "gitlab.odds.team/worklog/api.odds-worklog/business/models"
)

// MockForGettingUsersByRole is a mock of ForGettingUsersByRole interface.
type MockForGettingUsersByRole struct {
	ctrl     *gomock.Controller
	recorder *MockForGettingUsersByRoleMockRecorder
}

// MockForGettingUsersByRoleMockRecorder is the mock recorder for MockForGettingUsersByRole.
type MockForGettingUsersByRoleMockRecorder struct {
	mock *MockForGettingUsersByRole
}

// NewMockForGettingUsersByRole creates a new mock instance.
func NewMockForGettingUsersByRole(ctrl *gomock.Controller) *MockForGettingUsersByRole {
	mock := &MockForGettingUsersByRole{ctrl: ctrl}
	mock.recorder = &MockForGettingUsersByRoleMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockForGettingUsersByRole) EXPECT() *MockForGettingUsersByRoleMockRecorder {
	return m.recorder
}

// GetByRole mocks base method.
func (m *MockForGettingUsersByRole) GetByRole(role string) ([]*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByRole", role)
	ret0, _ := ret[0].([]*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByRole indicates an expected call of GetByRole.
func (mr *MockForGettingUsersByRoleMockRecorder) GetByRole(role interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByRole", reflect.TypeOf((*MockForGettingUsersByRole)(nil).GetByRole), role)
}
