// Code generated by MockGen. DO NOT EDIT.
// Source: gitlab.odds.team/worklog/api.odds-worklog/business/usecases (interfaces: ForLoggingSAPExportFailure)

// Package mock_usecases is a generated GoMock package.
package mock_usecases

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	models "gitlab.odds.team/worklog/api.odds-worklog/business/models"
)

// MockForLoggingSAPExportFailure is a mock of ForLoggingSAPExportFailure interface.
type MockForLoggingSAPExportFailure struct {
	ctrl     *gomock.Controller
	recorder *MockForLoggingSAPExportFailureMockRecorder
}

// MockForLoggingSAPExportFailureMockRecorder is the mock recorder for MockForLoggingSAPExportFailure.
type MockForLoggingSAPExportFailureMockRecorder struct {
	mock *MockForLoggingSAPExportFailure
}

// NewMockForLoggingSAPExportFailure creates a new mock instance.
func NewMockForLoggingSAPExportFailure(ctrl *gomock.Controller) *MockForLoggingSAPExportFailure {
	mock := &MockForLoggingSAPExportFailure{ctrl: ctrl}
	mock.recorder = &MockForLoggingSAPExportFailureMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockForLoggingSAPExportFailure) EXPECT() *MockForLoggingSAPExportFailureMockRecorder {
	return m.recorder
}

// LogSAPExportFailure mocks base method.
func (m *MockForLoggingSAPExportFailure) LogSAPExportFailure(arg0 *models.SAPExportFailureLog) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LogSAPExportFailure", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// LogSAPExportFailure indicates an expected call of LogSAPExportFailure.
func (mr *MockForLoggingSAPExportFailureMockRecorder) LogSAPExportFailure(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LogSAPExportFailure", reflect.TypeOf((*MockForLoggingSAPExportFailure)(nil).LogSAPExportFailure), arg0)
}
