// Code generated by MockGen. DO NOT EDIT.
// Source: business/usecases/sync_income_for_timesheet_driving_ports.go

// Package mock_usecases is a generated GoMock package.
package mock_usecases

import (
	gomock "github.com/golang/mock/gomock"
	models "gitlab.odds.team/worklog/api.odds-worklog/business/models"
	reflect "reflect"
)

// MockForSyncingIncomeForTimesheet is a mock of ForSyncingIncomeForTimesheet interface
type MockForSyncingIncomeForTimesheet struct {
	ctrl     *gomock.Controller
	recorder *MockForSyncingIncomeForTimesheetMockRecorder
}

// MockForSyncingIncomeForTimesheetMockRecorder is the mock recorder for MockForSyncingIncomeForTimesheet
type MockForSyncingIncomeForTimesheetMockRecorder struct {
	mock *MockForSyncingIncomeForTimesheet
}

// NewMockForSyncingIncomeForTimesheet creates a new mock instance
func NewMockForSyncingIncomeForTimesheet(ctrl *gomock.Controller) *MockForSyncingIncomeForTimesheet {
	mock := &MockForSyncingIncomeForTimesheet{ctrl: ctrl}
	mock.recorder = &MockForSyncingIncomeForTimesheetMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockForSyncingIncomeForTimesheet) EXPECT() *MockForSyncingIncomeForTimesheetMockRecorder {
	return m.recorder
}

// SyncFromEvent mocks base method
func (m *MockForSyncingIncomeForTimesheet) SyncFromEvent(evt models.TimesheetMonthlySummaryEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SyncFromEvent", evt)
	ret0, _ := ret[0].(error)
	return ret0
}

// SyncFromEvent indicates an expected call of SyncFromEvent
func (mr *MockForSyncingIncomeForTimesheetMockRecorder) SyncFromEvent(evt interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SyncFromEvent", reflect.TypeOf((*MockForSyncingIncomeForTimesheet)(nil).SyncFromEvent), evt)
}
