// Code generated by MockGen. DO NOT EDIT.
// Source: business/usecases/sync_income_from_timesheet_driving_ports.go

// Package mock_usecases is a generated GoMock package.
package mock_usecases

import (
	gomock "github.com/golang/mock/gomock"
	models "gitlab.odds.team/worklog/api.odds-worklog/business/models"
	reflect "reflect"
)

// MockForSyncingIncomeFromTimesheet is a mock of ForSyncingIncomeFromTimesheet interface
type MockForSyncingIncomeFromTimesheet struct {
	ctrl     *gomock.Controller
	recorder *MockForSyncingIncomeFromTimesheetMockRecorder
}

// MockForSyncingIncomeFromTimesheetMockRecorder is the mock recorder for MockForSyncingIncomeFromTimesheet
type MockForSyncingIncomeFromTimesheetMockRecorder struct {
	mock *MockForSyncingIncomeFromTimesheet
}

// NewMockForSyncingIncomeFromTimesheet creates a new mock instance
func NewMockForSyncingIncomeFromTimesheet(ctrl *gomock.Controller) *MockForSyncingIncomeFromTimesheet {
	mock := &MockForSyncingIncomeFromTimesheet{ctrl: ctrl}
	mock.recorder = &MockForSyncingIncomeFromTimesheetMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockForSyncingIncomeFromTimesheet) EXPECT() *MockForSyncingIncomeFromTimesheetMockRecorder {
	return m.recorder
}

// SyncFromEvent mocks base method
func (m *MockForSyncingIncomeFromTimesheet) SyncFromEvent(evt models.TimesheetMonthlySummaryEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SyncFromEvent", evt)
	ret0, _ := ret[0].(error)
	return ret0
}

// SyncFromEvent indicates an expected call of SyncFromEvent
func (mr *MockForSyncingIncomeFromTimesheetMockRecorder) SyncFromEvent(evt interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SyncFromEvent", reflect.TypeOf((*MockForSyncingIncomeFromTimesheet)(nil).SyncFromEvent), evt)
}
