// Code generated by MockGen. DO NOT EDIT.
// Source: business/usecases/sync_income_from_timesheet_driven_ports.go

// Package mock_usecases is a generated GoMock package.
package mock_usecases

import (
	gomock "github.com/golang/mock/gomock"
	models "gitlab.odds.team/worklog/api.odds-worklog/business/models"
	reflect "reflect"
	time "time"
)

// MockForGettingIncomeFromTimesheet is a mock of ForGettingIncomeFromTimesheet interface
type MockForGettingIncomeFromTimesheet struct {
	ctrl     *gomock.Controller
	recorder *MockForGettingIncomeFromTimesheetMockRecorder
}

// MockForGettingIncomeFromTimesheetMockRecorder is the mock recorder for MockForGettingIncomeFromTimesheet
type MockForGettingIncomeFromTimesheetMockRecorder struct {
	mock *MockForGettingIncomeFromTimesheet
}

// NewMockForGettingIncomeFromTimesheet creates a new mock instance
func NewMockForGettingIncomeFromTimesheet(ctrl *gomock.Controller) *MockForGettingIncomeFromTimesheet {
	mock := &MockForGettingIncomeFromTimesheet{ctrl: ctrl}
	mock.recorder = &MockForGettingIncomeFromTimesheetMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockForGettingIncomeFromTimesheet) EXPECT() *MockForGettingIncomeFromTimesheetMockRecorder {
	return m.recorder
}

// GetByUserYearMonth mocks base method
func (m *MockForGettingIncomeFromTimesheet) GetByUserYearMonth(userID string, year int, month time.Month) (*models.IncomeFromTimesheet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUserYearMonth", userID, year, month)
	ret0, _ := ret[0].(*models.IncomeFromTimesheet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUserYearMonth indicates an expected call of GetByUserYearMonth
func (mr *MockForGettingIncomeFromTimesheetMockRecorder) GetByUserYearMonth(userID, year, month interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUserYearMonth", reflect.TypeOf((*MockForGettingIncomeFromTimesheet)(nil).GetByUserYearMonth), userID, year, month)
}

// Add mocks base method
func (m *MockForGettingIncomeFromTimesheet) Add(income *models.IncomeFromTimesheet) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Add", income)
	ret0, _ := ret[0].(error)
	return ret0
}

// Add indicates an expected call of Add
func (mr *MockForGettingIncomeFromTimesheetMockRecorder) Add(income interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockForGettingIncomeFromTimesheet)(nil).Add), income)
}

// Update mocks base method
func (m *MockForGettingIncomeFromTimesheet) Update(income *models.IncomeFromTimesheet) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", income)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update
func (mr *MockForGettingIncomeFromTimesheetMockRecorder) Update(income interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockForGettingIncomeFromTimesheet)(nil).Update), income)
}

// MockForGettingTimesheetUser is a mock of ForGettingTimesheetUser interface
type MockForGettingTimesheetUser struct {
	ctrl     *gomock.Controller
	recorder *MockForGettingTimesheetUserMockRecorder
}

// MockForGettingTimesheetUserMockRecorder is the mock recorder for MockForGettingTimesheetUser
type MockForGettingTimesheetUserMockRecorder struct {
	mock *MockForGettingTimesheetUser
}

// NewMockForGettingTimesheetUser creates a new mock instance
func NewMockForGettingTimesheetUser(ctrl *gomock.Controller) *MockForGettingTimesheetUser {
	mock := &MockForGettingTimesheetUser{ctrl: ctrl}
	mock.recorder = &MockForGettingTimesheetUserMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockForGettingTimesheetUser) EXPECT() *MockForGettingTimesheetUserMockRecorder {
	return m.recorder
}

// GetByEmail mocks base method
func (m *MockForGettingTimesheetUser) GetByEmail(email string) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByEmail", email)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByEmail indicates an expected call of GetByEmail
func (mr *MockForGettingTimesheetUserMockRecorder) GetByEmail(email interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByEmail", reflect.TypeOf((*MockForGettingTimesheetUser)(nil).GetByEmail), email)
}

// MockForLoggingTimesheetEvent is a mock of ForLoggingTimesheetEvent interface
type MockForLoggingTimesheetEvent struct {
	ctrl     *gomock.Controller
	recorder *MockForLoggingTimesheetEventMockRecorder
}

// MockForLoggingTimesheetEventMockRecorder is the mock recorder for MockForLoggingTimesheetEvent
type MockForLoggingTimesheetEventMockRecorder struct {
	mock *MockForLoggingTimesheetEvent
}

// NewMockForLoggingTimesheetEvent creates a new mock instance
func NewMockForLoggingTimesheetEvent(ctrl *gomock.Controller) *MockForLoggingTimesheetEvent {
	mock := &MockForLoggingTimesheetEvent{ctrl: ctrl}
	mock.recorder = &MockForLoggingTimesheetEventMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockForLoggingTimesheetEvent) EXPECT() *MockForLoggingTimesheetEventMockRecorder {
	return m.recorder
}

// Save mocks base method
func (m *MockForLoggingTimesheetEvent) Save(evt models.TimesheetMonthlySummaryEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", evt)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save
func (mr *MockForLoggingTimesheetEventMockRecorder) Save(evt interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockForLoggingTimesheetEvent)(nil).Save), evt)
}
