// Code generated by MockGen. DO NOT EDIT.
// Source: business/usecases/sync_income_for_timesheet_driven_ports.go

// Package mock_usecases is a generated GoMock package.
package mock_usecases

import (
	gomock "github.com/golang/mock/gomock"
	models "gitlab.odds.team/worklog/api.odds-worklog/business/models"
	reflect "reflect"
	time "time"
)

// MockForGettingIncomeForTimesheet is a mock of ForGettingIncomeForTimesheet interface
type MockForGettingIncomeForTimesheet struct {
	ctrl     *gomock.Controller
	recorder *MockForGettingIncomeForTimesheetMockRecorder
}

// MockForGettingIncomeForTimesheetMockRecorder is the mock recorder for MockForGettingIncomeForTimesheet
type MockForGettingIncomeForTimesheetMockRecorder struct {
	mock *MockForGettingIncomeForTimesheet
}

// NewMockForGettingIncomeForTimesheet creates a new mock instance
func NewMockForGettingIncomeForTimesheet(ctrl *gomock.Controller) *MockForGettingIncomeForTimesheet {
	mock := &MockForGettingIncomeForTimesheet{ctrl: ctrl}
	mock.recorder = &MockForGettingIncomeForTimesheetMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockForGettingIncomeForTimesheet) EXPECT() *MockForGettingIncomeForTimesheetMockRecorder {
	return m.recorder
}

// GetByUserYearMonth mocks base method
func (m *MockForGettingIncomeForTimesheet) GetByUserYearMonth(userID string, year int, month time.Month) (*models.IncomeForTimesheet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUserYearMonth", userID, year, month)
	ret0, _ := ret[0].(*models.IncomeForTimesheet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUserYearMonth indicates an expected call of GetByUserYearMonth
func (mr *MockForGettingIncomeForTimesheetMockRecorder) GetByUserYearMonth(userID, year, month interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUserYearMonth", reflect.TypeOf((*MockForGettingIncomeForTimesheet)(nil).GetByUserYearMonth), userID, year, month)
}

// Add mocks base method
func (m *MockForGettingIncomeForTimesheet) Add(income *models.IncomeForTimesheet) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Add", income)
	ret0, _ := ret[0].(error)
	return ret0
}

// Add indicates an expected call of Add
func (mr *MockForGettingIncomeForTimesheetMockRecorder) Add(income interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockForGettingIncomeForTimesheet)(nil).Add), income)
}

// Update mocks base method
func (m *MockForGettingIncomeForTimesheet) Update(income *models.IncomeForTimesheet) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", income)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update
func (mr *MockForGettingIncomeForTimesheetMockRecorder) Update(income interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockForGettingIncomeForTimesheet)(nil).Update), income)
}

// MockForGettingTimesheetUser is a mock of ForGettingTimesheetUser interface
type MockForGettingTimesheetUser struct {
	ctrl     *gomock.Controller
	recorder *MockForGettingTimesheetUserMockRecorder
}

// MockForGettingTimesheetUserMockRecorder is the mock recorder for MockForGettingTimesheetUser
type MockForGettingTimesheetUserMockRecorder struct {
	mock *MockForGettingTimesheetUser
}

// NewMockForGettingTimesheetUser creates a new mock instance
func NewMockForGettingTimesheetUser(ctrl *gomock.Controller) *MockForGettingTimesheetUser {
	mock := &MockForGettingTimesheetUser{ctrl: ctrl}
	mock.recorder = &MockForGettingTimesheetUserMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockForGettingTimesheetUser) EXPECT() *MockForGettingTimesheetUserMockRecorder {
	return m.recorder
}

// GetByEmail mocks base method
func (m *MockForGettingTimesheetUser) GetByEmail(email string) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByEmail", email)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByEmail indicates an expected call of GetByEmail
func (mr *MockForGettingTimesheetUserMockRecorder) GetByEmail(email interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByEmail", reflect.TypeOf((*MockForGettingTimesheetUser)(nil).GetByEmail), email)
}
