// Code generated by MockGen. DO NOT EDIT.
// Source: usecases/update_income_driven_ports.go

// Package mock_usecases is a generated GoMock package.
package mock_usecases

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	models "gitlab.odds.team/worklog/api.odds-worklog/business/models"
)

// MockForUpdatingUserIncome is a mock of ForUpdatingUserIncome interface.
type MockForUpdatingUserIncome struct {
	ctrl     *gomock.Controller
	recorder *MockForUpdatingUserIncomeMockRecorder
}

// MockForUpdatingUserIncomeMockRecorder is the mock recorder for MockForUpdatingUserIncome.
type MockForUpdatingUserIncomeMockRecorder struct {
	mock *MockForUpdatingUserIncome
}

// NewMockForUpdatingUserIncome creates a new mock instance.
func NewMockForUpdatingUserIncome(ctrl *gomock.Controller) *MockForUpdatingUserIncome {
	mock := &MockForUpdatingUserIncome{ctrl: ctrl}
	mock.recorder = &MockForUpdatingUserIncomeMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockForUpdatingUserIncome) EXPECT() *MockForUpdatingUserIncomeMockRecorder {
	return m.recorder
}

// GetIncomeByID mocks base method.
func (m *MockForUpdatingUserIncome) GetIncomeByID(incID, uID string) (*models.Income, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIncomeByID", incID, uID)
	ret0, _ := ret[0].(*models.Income)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetIncomeByID indicates an expected call of GetIncomeByID.
func (mr *MockForUpdatingUserIncomeMockRecorder) GetIncomeByID(incID, uID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIncomeByID", reflect.TypeOf((*MockForUpdatingUserIncome)(nil).GetIncomeByID), incID, uID)
}

// UpdateIncome mocks base method.
func (m *MockForUpdatingUserIncome) UpdateIncome(income *models.Income) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateIncome", income)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateIncome indicates an expected call of UpdateIncome.
func (mr *MockForUpdatingUserIncomeMockRecorder) UpdateIncome(income interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateIncome", reflect.TypeOf((*MockForUpdatingUserIncome)(nil).UpdateIncome), income)
}

// MockForUsingUpdateIncome is a mock of ForUsingUpdateIncome interface.
type MockForUsingUpdateIncome struct {
	ctrl     *gomock.Controller
	recorder *MockForUsingUpdateIncomeMockRecorder
}

// MockForUsingUpdateIncomeMockRecorder is the mock recorder for MockForUsingUpdateIncome.
type MockForUsingUpdateIncomeMockRecorder struct {
	mock *MockForUsingUpdateIncome
}

// NewMockForUsingUpdateIncome creates a new mock instance.
func NewMockForUsingUpdateIncome(ctrl *gomock.Controller) *MockForUsingUpdateIncome {
	mock := &MockForUsingUpdateIncome{ctrl: ctrl}
	mock.recorder = &MockForUsingUpdateIncomeMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockForUsingUpdateIncome) EXPECT() *MockForUsingUpdateIncomeMockRecorder {
	return m.recorder
}

// UpdateIncome mocks base method.
func (m *MockForUsingUpdateIncome) UpdateIncome(id string, req *models.IncomeReq, uid string) (*models.Income, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateIncome", id, req, uid)
	ret0, _ := ret[0].(*models.Income)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateIncome indicates an expected call of UpdateIncome.
func (mr *MockForUsingUpdateIncomeMockRecorder) UpdateIncome(id, req, uid interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateIncome", reflect.TypeOf((*MockForUsingUpdateIncome)(nil).UpdateIncome), id, req, uid)
}
