// Code generated by MockGen. DO NOT EDIT.
// Source: api/invoice/interface.go

// Package mock_invoice is a generated GoMock package.
package mock_invoice

import (
	gomock "github.com/golang/mock/gomock"
	models "gitlab.odds.team/worklog/api.odds-worklog/models"
	reflect "reflect"
)

// MockUsecase is a mock of Usecase interface
type MockUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockUsecaseMockRecorder
}

// MockUsecaseMockRecorder is the mock recorder for MockUsecase
type MockUsecaseMockRecorder struct {
	mock *MockUsecase
}

// NewMockUsecase creates a new mock instance
func NewMockUsecase(ctrl *gomock.Controller) *MockUsecase {
	mock := &MockUsecase{ctrl: ctrl}
	mock.recorder = &MockUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockUsecase) EXPECT() *MockUsecaseMockRecorder {
	return m.recorder
}

// Create mocks base method
func (m *MockUsecase) Create(i *models.Invoice) (*models.Invoice, error) {
	ret := m.ctrl.Call(m, "Create", i)
	ret0, _ := ret[0].(*models.Invoice)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create
func (mr *MockUsecaseMockRecorder) Create(i interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockUsecase)(nil).Create), i)
}

// Get mocks base method
func (m *MockUsecase) Get() ([]*models.Invoice, error) {
	ret := m.ctrl.Call(m, "Get")
	ret0, _ := ret[0].([]*models.Invoice)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get
func (mr *MockUsecaseMockRecorder) Get() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockUsecase)(nil).Get))
}

// GetByPO mocks base method
func (m *MockUsecase) GetByPO(id string) ([]*models.Invoice, error) {
	ret := m.ctrl.Call(m, "GetByPO", id)
	ret0, _ := ret[0].([]*models.Invoice)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByPO indicates an expected call of GetByPO
func (mr *MockUsecaseMockRecorder) GetByPO(id interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByPO", reflect.TypeOf((*MockUsecase)(nil).GetByPO), id)
}

// GetByID mocks base method
func (m *MockUsecase) GetByID(id string) (*models.Invoice, error) {
	ret := m.ctrl.Call(m, "GetByID", id)
	ret0, _ := ret[0].(*models.Invoice)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID
func (mr *MockUsecaseMockRecorder) GetByID(id interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockUsecase)(nil).GetByID), id)
}

// NextNo mocks base method
func (m *MockUsecase) NextNo(id string) (string, error) {
	ret := m.ctrl.Call(m, "NextNo", id)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NextNo indicates an expected call of NextNo
func (mr *MockUsecaseMockRecorder) NextNo(id interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NextNo", reflect.TypeOf((*MockUsecase)(nil).NextNo), id)
}

// Delete mocks base method
func (m *MockUsecase) Delete(id string) error {
	ret := m.ctrl.Call(m, "Delete", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete
func (mr *MockUsecaseMockRecorder) Delete(id interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockUsecase)(nil).Delete), id)
}

// MockRepository is a mock of Repository interface
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method
func (m *MockRepository) Create(i *models.Invoice) (*models.Invoice, error) {
	ret := m.ctrl.Call(m, "Create", i)
	ret0, _ := ret[0].(*models.Invoice)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create
func (mr *MockRepositoryMockRecorder) Create(i interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRepository)(nil).Create), i)
}

// Get mocks base method
func (m *MockRepository) Get() ([]*models.Invoice, error) {
	ret := m.ctrl.Call(m, "Get")
	ret0, _ := ret[0].([]*models.Invoice)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get
func (mr *MockRepositoryMockRecorder) Get() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockRepository)(nil).Get))
}

// GetByPO mocks base method
func (m *MockRepository) GetByPO(id string) ([]*models.Invoice, error) {
	ret := m.ctrl.Call(m, "GetByPO", id)
	ret0, _ := ret[0].([]*models.Invoice)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByPO indicates an expected call of GetByPO
func (mr *MockRepositoryMockRecorder) GetByPO(id interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByPO", reflect.TypeOf((*MockRepository)(nil).GetByPO), id)
}

// GetByID mocks base method
func (m *MockRepository) GetByID(id string) (*models.Invoice, error) {
	ret := m.ctrl.Call(m, "GetByID", id)
	ret0, _ := ret[0].(*models.Invoice)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID
func (mr *MockRepositoryMockRecorder) GetByID(id interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockRepository)(nil).GetByID), id)
}

// Last mocks base method
func (m *MockRepository) Last(id string) (*models.Invoice, error) {
	ret := m.ctrl.Call(m, "Last", id)
	ret0, _ := ret[0].(*models.Invoice)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Last indicates an expected call of Last
func (mr *MockRepositoryMockRecorder) Last(id interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Last", reflect.TypeOf((*MockRepository)(nil).Last), id)
}

// Delete mocks base method
func (m *MockRepository) Delete(id string) error {
	ret := m.ctrl.Call(m, "Delete", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete
func (mr *MockRepositoryMockRecorder) Delete(id interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockRepository)(nil).Delete), id)
}
