// Code generated by MockGen. DO NOT EDIT.
// Source: api/po/interface.go

// Package mock_po is a generated GoMock package.
package mock_po

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	models "gitlab.odds.team/worklog/api.odds-worklog/models"
)

// MockRepository is a mock of Repository interface
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method
func (m *MockRepository) Create(po *models.Po) (*models.Po, error) {
	ret := m.ctrl.Call(m, "Create", po)
	ret0, _ := ret[0].(*models.Po)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create
func (mr *MockRepositoryMockRecorder) Create(po interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRepository)(nil).Create), po)
}

// Update mocks base method
func (m *MockRepository) Update(po *models.Po) (*models.Po, error) {
	ret := m.ctrl.Call(m, "Update", po)
	ret0, _ := ret[0].(*models.Po)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update
func (mr *MockRepositoryMockRecorder) Update(po interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockRepository)(nil).Update), po)
}

// Get mocks base method
func (m *MockRepository) Get() ([]*models.Po, error) {
	ret := m.ctrl.Call(m, "Get")
	ret0, _ := ret[0].([]*models.Po)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get
func (mr *MockRepositoryMockRecorder) Get() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockRepository)(nil).Get))
}

// GetByID mocks base method
func (m *MockRepository) GetByID(id string) (*models.Po, error) {
	ret := m.ctrl.Call(m, "GetByID", id)
	ret0, _ := ret[0].(*models.Po)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID
func (mr *MockRepositoryMockRecorder) GetByID(id interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockRepository)(nil).GetByID), id)
}

// GetByCusID mocks base method
func (m *MockRepository) GetByCusID(id string) ([]*models.Po, error) {
	ret := m.ctrl.Call(m, "GetByCusID", id)
	ret0, _ := ret[0].([]*models.Po)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByCusID indicates an expected call of GetByCusID
func (mr *MockRepositoryMockRecorder) GetByCusID(id interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByCusID", reflect.TypeOf((*MockRepository)(nil).GetByCusID), id)
}

// Delete mocks base method
func (m *MockRepository) Delete(id string) error {
	ret := m.ctrl.Call(m, "Delete", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete
func (mr *MockRepositoryMockRecorder) Delete(id interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockRepository)(nil).Delete), id)
}

// MockUsecase is a mock of Usecase interface
type MockUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockUsecaseMockRecorder
}

// MockUsecaseMockRecorder is the mock recorder for MockUsecase
type MockUsecaseMockRecorder struct {
	mock *MockUsecase
}

// NewMockUsecase creates a new mock instance
func NewMockUsecase(ctrl *gomock.Controller) *MockUsecase {
	mock := &MockUsecase{ctrl: ctrl}
	mock.recorder = &MockUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockUsecase) EXPECT() *MockUsecaseMockRecorder {
	return m.recorder
}

// Create mocks base method
func (m *MockUsecase) Create(po *models.Po) (*models.Po, error) {
	ret := m.ctrl.Call(m, "Create", po)
	ret0, _ := ret[0].(*models.Po)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create
func (mr *MockUsecaseMockRecorder) Create(po interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockUsecase)(nil).Create), po)
}

// Update mocks base method
func (m *MockUsecase) Update(po *models.Po) (*models.Po, error) {
	ret := m.ctrl.Call(m, "Update", po)
	ret0, _ := ret[0].(*models.Po)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update
func (mr *MockUsecaseMockRecorder) Update(po interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockUsecase)(nil).Update), po)
}

// Get mocks base method
func (m *MockUsecase) Get() ([]*models.Po, error) {
	ret := m.ctrl.Call(m, "Get")
	ret0, _ := ret[0].([]*models.Po)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get
func (mr *MockUsecaseMockRecorder) Get() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockUsecase)(nil).Get))
}

// GetByID mocks base method
func (m *MockUsecase) GetByID(id string) (*models.Po, error) {
	ret := m.ctrl.Call(m, "GetByID", id)
	ret0, _ := ret[0].(*models.Po)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID
func (mr *MockUsecaseMockRecorder) GetByID(id interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockUsecase)(nil).GetByID), id)
}

// GetByCusID mocks base method
func (m *MockUsecase) GetByCusID(id string) ([]*models.Po, error) {
	ret := m.ctrl.Call(m, "GetByCusID", id)
	ret0, _ := ret[0].([]*models.Po)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByCusID indicates an expected call of GetByCusID
func (mr *MockUsecaseMockRecorder) GetByCusID(id interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByCusID", reflect.TypeOf((*MockUsecase)(nil).GetByCusID), id)
}

// Delete mocks base method
func (m *MockUsecase) Delete(id string) error {
	ret := m.ctrl.Call(m, "Delete", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete
func (mr *MockUsecaseMockRecorder) Delete(id interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockUsecase)(nil).Delete), id)
}
