// Code generated by MockGen. DO NOT EDIT.
// Source: api/income/interface.go

// Package mock_income is a generated GoMock package.
package mock_income

import (
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
	models "gitlab.odds.team/worklog/api.odds-worklog/business/models"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// AddIncome mocks base method.
func (m *MockRepository) AddIncome(u *models.Income) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddIncome", u)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddIncome indicates an expected call of AddIncome.
func (mr *MockRepositoryMockRecorder) AddIncome(u interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddIncome", reflect.TypeOf((*MockRepository)(nil).AddIncome), u)
}

// AddIncomeOnSpecificTime mocks base method.
func (m *MockRepository) AddIncomeOnSpecificTime(u *models.Income, t time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddIncomeOnSpecificTime", u, t)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddIncomeOnSpecificTime indicates an expected call of AddIncomeOnSpecificTime.
func (mr *MockRepositoryMockRecorder) AddIncomeOnSpecificTime(u, t interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddIncomeOnSpecificTime", reflect.TypeOf((*MockRepository)(nil).AddIncomeOnSpecificTime), u, t)
}

// GetIncomeByID mocks base method.
func (m *MockRepository) GetIncomeByID(incID, uID string) (*models.Income, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIncomeByID", incID, uID)
	ret0, _ := ret[0].(*models.Income)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetIncomeByID indicates an expected call of GetIncomeByID.
func (mr *MockRepositoryMockRecorder) GetIncomeByID(incID, uID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIncomeByID", reflect.TypeOf((*MockRepository)(nil).GetIncomeByID), incID, uID)
}

// GetIncomeByStartDateAndEndDate mocks base method.
func (m *MockRepository) GetIncomeByStartDateAndEndDate(role string, startDate, endDate time.Time) (*models.Income, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIncomeByStartDateAndEndDate", role, startDate, endDate)
	ret0, _ := ret[0].(*models.Income)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetIncomeByStartDateAndEndDate indicates an expected call of GetIncomeByStartDateAndEndDate.
func (mr *MockRepositoryMockRecorder) GetIncomeByStartDateAndEndDate(role, startDate, endDate interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIncomeByStartDateAndEndDate", reflect.TypeOf((*MockRepository)(nil).GetIncomeByStartDateAndEndDate), role, startDate, endDate)
}

// GetIncomeByUserID mocks base method.
func (m *MockRepository) GetIncomeByUserID(uID string, fromYear int, fromMonth time.Month) (*models.Income, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIncomeByUserID", uID, fromYear, fromMonth)
	ret0, _ := ret[0].(*models.Income)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetIncomeByUserID indicates an expected call of GetIncomeByUserID.
func (mr *MockRepositoryMockRecorder) GetIncomeByUserID(uID, fromYear, fromMonth interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIncomeByUserID", reflect.TypeOf((*MockRepository)(nil).GetIncomeByUserID), uID, fromYear, fromMonth)
}

// GetIncomeByUserIdAllMonth mocks base method.
func (m *MockRepository) GetIncomeByUserIdAllMonth(userId string) ([]*models.Income, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIncomeByUserIdAllMonth", userId)
	ret0, _ := ret[0].([]*models.Income)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetIncomeByUserIdAllMonth indicates an expected call of GetIncomeByUserIdAllMonth.
func (mr *MockRepositoryMockRecorder) GetIncomeByUserIdAllMonth(userId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIncomeByUserIdAllMonth", reflect.TypeOf((*MockRepository)(nil).GetIncomeByUserIdAllMonth), userId)
}

// GetIncomeUserByYearMonth mocks base method.
func (m *MockRepository) GetIncomeUserByYearMonth(id string, fromYear int, fromMonth time.Month) (*models.Income, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIncomeUserByYearMonth", id, fromYear, fromMonth)
	ret0, _ := ret[0].(*models.Income)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetIncomeUserByYearMonth indicates an expected call of GetIncomeUserByYearMonth.
func (mr *MockRepositoryMockRecorder) GetIncomeUserByYearMonth(id, fromYear, fromMonth interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIncomeUserByYearMonth", reflect.TypeOf((*MockRepository)(nil).GetIncomeUserByYearMonth), id, fromYear, fromMonth)
}

// SaveStudentLoans mocks base method.
func (m *MockRepository) SaveStudentLoans(loans models.StudentLoanList) int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveStudentLoans", loans)
	ret0, _ := ret[0].(int)
	return ret0
}

// SaveStudentLoans indicates an expected call of SaveStudentLoans.
func (mr *MockRepositoryMockRecorder) SaveStudentLoans(loans interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveStudentLoans", reflect.TypeOf((*MockRepository)(nil).SaveStudentLoans), loans)
}

// UpdateExportStatus mocks base method.
func (m *MockRepository) UpdateExportStatus(id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateExportStatus", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateExportStatus indicates an expected call of UpdateExportStatus.
func (mr *MockRepositoryMockRecorder) UpdateExportStatus(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateExportStatus", reflect.TypeOf((*MockRepository)(nil).UpdateExportStatus), id)
}

// UpdateIncome mocks base method.
func (m *MockRepository) UpdateIncome(income *models.Income) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateIncome", income)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateIncome indicates an expected call of UpdateIncome.
func (mr *MockRepositoryMockRecorder) UpdateIncome(income interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateIncome", reflect.TypeOf((*MockRepository)(nil).UpdateIncome), income)
}
