// Code generated by MockGen. DO NOT EDIT.
// Source: api/user/interface.go

// Package mock_user is a generated GoMock package.
package mock_user

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	models "gitlab.odds.team/worklog/api.odds-worklog/models"
)

// MockRepository is a mock of Repository interface
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// CreateCustomer mocks base method
func (m *MockRepository) CreateCustomer(u *models.Customer) (*models.Customer, error) {
	ret := m.ctrl.Call(m, "CreateCustomer", u)
	ret0, _ := ret[0].(*models.Customer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateCustomer indicates an expected call of CreateCustomer
func (mr *MockRepositoryMockRecorder) CreateCustomer(u interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCustomer", reflect.TypeOf((*MockRepository)(nil).CreateCustomer), u)
}

// GetCustomers mocks base method
func (m *MockRepository) GetCustomers() ([]*models.Customer, error) {
	ret := m.ctrl.Call(m, "GetCustomers")
	ret0, _ := ret[0].([]*models.Customer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCustomers indicates an expected call of GetCustomers
func (mr *MockRepositoryMockRecorder) GetCustomers() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCustomers", reflect.TypeOf((*MockRepository)(nil).GetCustomers))
}

// GetCustomerByID mocks base method
func (m *MockRepository) GetCustomerByID(id string) (*models.Customer, error) {
	ret := m.ctrl.Call(m, "GetCustomerByID", id)
	ret0, _ := ret[0].(*models.Customer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCustomerByID indicates an expected call of GetCustomerByID
func (mr *MockRepositoryMockRecorder) GetCustomerByID(id interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCustomerByID", reflect.TypeOf((*MockRepository)(nil).GetCustomerByID), id)
}

// UpdateCustomer mocks base method
func (m *MockRepository) UpdateCustomer(u *models.Customer) (*models.Customer, error) {
	ret := m.ctrl.Call(m, "UpdateCustomer", u)
	ret0, _ := ret[0].(*models.Customer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateCustomer indicates an expected call of UpdateCustomer
func (mr *MockRepositoryMockRecorder) UpdateCustomer(u interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCustomer", reflect.TypeOf((*MockRepository)(nil).UpdateCustomer), u)
}

// DeleteCustomer mocks base method
func (m *MockRepository) DeleteCustomer(id string) error {
	ret := m.ctrl.Call(m, "DeleteCustomer", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteCustomer indicates an expected call of DeleteCustomer
func (mr *MockRepositoryMockRecorder) DeleteCustomer(id interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCustomer", reflect.TypeOf((*MockRepository)(nil).DeleteCustomer), id)
}

// MockUsecase is a mock of Usecase interface
type MockUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockUsecaseMockRecorder
}

// MockUsecaseMockRecorder is the mock recorder for MockUsecase
type MockUsecaseMockRecorder struct {
	mock *MockUsecase
}

// NewMockUsecase creates a new mock instance
func NewMockUsecase(ctrl *gomock.Controller) *MockUsecase {
	mock := &MockUsecase{ctrl: ctrl}
	mock.recorder = &MockUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockUsecase) EXPECT() *MockUsecaseMockRecorder {
	return m.recorder
}

// CreateCustomer mocks base method
func (m *MockUsecase) CreateCustomer(u *models.Customer) (*models.Customer, error) {
	ret := m.ctrl.Call(m, "CreateCustomer", u)
	ret0, _ := ret[0].(*models.Customer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateCustomer indicates an expected call of CreateCustomer
func (mr *MockUsecaseMockRecorder) CreateCustomer(u interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCustomer", reflect.TypeOf((*MockUsecase)(nil).CreateCustomer), u)
}

// GetCustomers mocks base method
func (m *MockUsecase) GetCustomers() ([]*models.Customer, error) {
	ret := m.ctrl.Call(m, "GetCustomers")
	ret0, _ := ret[0].([]*models.Customer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCustomers indicates an expected call of GetCustomers
func (mr *MockUsecaseMockRecorder) GetCustomers() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCustomers", reflect.TypeOf((*MockUsecase)(nil).GetCustomers))
}

// GetCustomerByID mocks base method
func (m *MockUsecase) GetCustomerByID(id string) (*models.Customer, error) {
	ret := m.ctrl.Call(m, "GetCustomerByID", id)
	ret0, _ := ret[0].(*models.Customer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCustomerByID indicates an expected call of GetCustomerByID
func (mr *MockUsecaseMockRecorder) GetCustomerByID(id interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCustomerByID", reflect.TypeOf((*MockUsecase)(nil).GetCustomerByID), id)
}

// UpdateCustomer mocks base method
func (m *MockUsecase) UpdateCustomer(u *models.Customer, isAdmin bool) (*models.Customer, error) {
	ret := m.ctrl.Call(m, "UpdateCustomer", u, isAdmin)
	ret0, _ := ret[0].(*models.Customer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateCustomer indicates an expected call of UpdateCustomer
func (mr *MockUsecaseMockRecorder) UpdateCustomer(u, isAdmin interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCustomer", reflect.TypeOf((*MockUsecase)(nil).UpdateCustomer), u, isAdmin)
}

// DeleteCustomer mocks base method
func (m *MockUsecase) DeleteCustomer(id string) error {
	ret := m.ctrl.Call(m, "DeleteCustomer", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteCustomer indicates an expected call of DeleteCustomer
func (mr *MockUsecaseMockRecorder) DeleteCustomer(id interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCustomer", reflect.TypeOf((*MockUsecase)(nil).DeleteCustomer), id)
}
