services:
  mongodb:
    extends:
      file: ../base/docker-compose.yaml
      service: mongodb
    volumes:
      - mongodbdata_odds_worklog:/data/db
      - ../../data/:/fixture/data/
    env_file:
      - .env

  keycloak:
    extends:
      file: ../base/docker-compose.yaml
      service: keycloak

volumes:
  mongodbdata_odds_worklog:
