services:
  mongodb:
    extends:
      file: ../base/docker-compose.yaml
      service: mongodb
    volumes:
      - mongodbdata_odds_worklog:/data/db
      - ../../data/:/fixture/data/
    env_file:
      - .env

  keycloak:
    extends:
      file: ../base/docker-compose.yaml
      service: keycloak

  rabbitmq:
    image: rabbitmq:3-management
    container_name: odds-worklog-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  mongodbdata_odds_worklog:
