// Code generated by MockGen. DO NOT EDIT.
// Source: api/usecases/adaptors.go

// Package mock_usecases is a generated GoMock package.
package mock_usecases

import (
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
	models "gitlab.odds.team/worklog/api.odds-worklog/models"
)

// MockForGettingIncomeData is a mock of ForGettingIncomeData interface.
type MockForGettingIncomeData struct {
	ctrl     *gomock.Controller
	recorder *MockForGettingIncomeDataMockRecorder
}

// MockForGettingIncomeDataMockRecorder is the mock recorder for MockForGettingIncomeData.
type MockForGettingIncomeDataMockRecorder struct {
	mock *MockForGettingIncomeData
}

// NewMockForGettingIncomeData creates a new mock instance.
func NewMockForGettingIncomeData(ctrl *gomock.Controller) *MockForGettingIncomeData {
	mock := &MockForGettingIncomeData{ctrl: ctrl}
	mock.recorder = &MockForGettingIncomeDataMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockForGettingIncomeData) EXPECT() *MockForGettingIncomeDataMockRecorder {
	return m.recorder
}

// GetAllIncomeByRoleStartDateAndEndDate mocks base method.
func (m *MockForGettingIncomeData) GetAllIncomeByRoleStartDateAndEndDate(role string, startDate, endDate time.Time) ([]*models.Income, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllIncomeByRoleStartDateAndEndDate", role, startDate, endDate)
	ret0, _ := ret[0].([]*models.Income)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllIncomeByRoleStartDateAndEndDate indicates an expected call of GetAllIncomeByRoleStartDateAndEndDate.
func (mr *MockForGettingIncomeDataMockRecorder) GetAllIncomeByRoleStartDateAndEndDate(role, startDate, endDate interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllIncomeByRoleStartDateAndEndDate", reflect.TypeOf((*MockForGettingIncomeData)(nil).GetAllIncomeByRoleStartDateAndEndDate), role, startDate, endDate)
}

// GetStudentLoans mocks base method.
func (m *MockForGettingIncomeData) GetStudentLoans() models.StudentLoanList {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStudentLoans")
	ret0, _ := ret[0].(models.StudentLoanList)
	return ret0
}

// GetStudentLoans indicates an expected call of GetStudentLoans.
func (mr *MockForGettingIncomeDataMockRecorder) GetStudentLoans() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStudentLoans", reflect.TypeOf((*MockForGettingIncomeData)(nil).GetStudentLoans))
}

// MockForControllingIncomeData is a mock of ForControllingIncomeData interface.
type MockForControllingIncomeData struct {
	ctrl     *gomock.Controller
	recorder *MockForControllingIncomeDataMockRecorder
}

// MockForControllingIncomeDataMockRecorder is the mock recorder for MockForControllingIncomeData.
type MockForControllingIncomeDataMockRecorder struct {
	mock *MockForControllingIncomeData
}

// NewMockForControllingIncomeData creates a new mock instance.
func NewMockForControllingIncomeData(ctrl *gomock.Controller) *MockForControllingIncomeData {
	mock := &MockForControllingIncomeData{ctrl: ctrl}
	mock.recorder = &MockForControllingIncomeDataMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockForControllingIncomeData) EXPECT() *MockForControllingIncomeDataMockRecorder {
	return m.recorder
}

// AddExport mocks base method.
func (m *MockForControllingIncomeData) AddExport(ep *models.Export) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddExport", ep)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddExport indicates an expected call of AddExport.
func (mr *MockForControllingIncomeDataMockRecorder) AddExport(ep interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddExport", reflect.TypeOf((*MockForControllingIncomeData)(nil).AddExport), ep)
}
