#!/bin/bash

AUTH_ARGS=(-u admin -p "$MONGO_DB_PASSWORD" --authenticationDatabase odds_worklog_db)
IMPORT_ARGS=(--host localhost --port 27017 -d odds_worklog_db --type json --maintainInsertionOrder --jsonArray)

docker exec odds-worklog-mongo mongoimport "${AUTH_ARGS[@]}" "${IMPORT_ARGS[@]}" \
  --collection user --file fixture/data/user.json

docker exec odds-worklog-mongo mongoimport "${AUTH_ARGS[@]}" "${IMPORT_ARGS[@]}" \
  --collection site --file fixture/data/site.json

docker exec odds-worklog-mongo mongoimport "${AUTH_ARGS[@]}" "${IMPORT_ARGS[@]}" \
  --collection consumer --file fixture/data/consumer.json

docker exec odds-worklog-mongo mongoimport "${AUTH_ARGS[@]}" "${IMPORT_ARGS[@]}" \
  --collection invoice --file fixture/data/invoice.json

./scripts/update_current_income
docker exec odds-worklog-mongo mongoimport "${AUTH_ARGS[@]}" "${IMPORT_ARGS[@]}" \
  --collection income --file fixture/data/income.json
