// Code generated by MockGen. DO NOT EDIT.
// Source: api/login/interface.go

// Package mock_login is a generated GoMock package.
package mock_login

import (
	gomock "github.com/golang/mock/gomock"
	models "gitlab.odds.team/worklog/api.odds-worklog/models"
	v2 "google.golang.org/api/oauth2/v2"
	reflect "reflect"
)

// MockUsecase is a mock of Usecase interface
type MockUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockUsecaseMockRecorder
}

// MockUsecaseMockRecorder is the mock recorder for MockUsecase
type MockUsecaseMockRecorder struct {
	mock *MockUsecase
}

// NewMockUsecase creates a new mock instance
func NewMockUsecase(ctrl *gomock.Controller) *MockUsecase {
	mock := &MockUsecase{ctrl: ctrl}
	mock.recorder = &MockUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockUsecase) EXPECT() *MockUsecaseMockRecorder {
	return m.recorder
}

// ManageLogin mocks base method
func (m *MockUsecase) ManageLogin(idToken string) (*models.Token, error) {
	ret := m.ctrl.Call(m, "ManageLogin", idToken)
	ret0, _ := ret[0].(*models.Token)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ManageLogin indicates an expected call of ManageLogin
func (mr *MockUsecaseMockRecorder) ManageLogin(idToken interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ManageLogin", reflect.TypeOf((*MockUsecase)(nil).ManageLogin), idToken)
}

// GetTokenInfo mocks base method
func (m *MockUsecase) GetTokenInfo(idToken string) (*v2.Tokeninfo, error) {
	ret := m.ctrl.Call(m, "GetTokenInfo", idToken)
	ret0, _ := ret[0].(*v2.Tokeninfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTokenInfo indicates an expected call of GetTokenInfo
func (mr *MockUsecaseMockRecorder) GetTokenInfo(idToken interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTokenInfo", reflect.TypeOf((*MockUsecase)(nil).GetTokenInfo), idToken)
}

// CreateUser mocks base method
func (m *MockUsecase) CreateUser(email string) (*models.User, error) {
	ret := m.ctrl.Call(m, "CreateUser", email)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUser indicates an expected call of CreateUser
func (mr *MockUsecaseMockRecorder) CreateUser(email interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockUsecase)(nil).CreateUser), email)
}
