// Code generated by MockGen. DO NOT EDIT.
// Source: api/login/interface.go

// Package mock_login is a generated GoMock package.
package mock_login

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	models "gitlab.odds.team/worklog/api.odds-worklog/models"
)

// MockUsecase is a mock of Usecase interface.
type MockUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockUsecaseMockRecorder
}

// MockUsecaseMockRecorder is the mock recorder for MockUsecase.
type MockUsecaseMockRecorder struct {
	mock *MockUsecase
}

// NewMockUsecase creates a new mock instance.
func NewMockUsecase(ctrl *gomock.Controller) *MockUsecase {
	mock := &MockUsecase{ctrl: ctrl}
	mock.recorder = &MockUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUsecase) EXPECT() *MockUsecaseMockRecorder {
	return m.recorder
}

// CreateUser mocks base method.
func (m *MockUsecase) CreateUser(email string) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", email)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockUsecaseMockRecorder) CreateUser(email interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockUsecase)(nil).CreateUser), email)
}

// CreateUserAndValidateEmail mocks base method.
func (m *MockUsecase) CreateUserAndValidateEmail(email string) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUserAndValidateEmail", email)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUserAndValidateEmail indicates an expected call of CreateUserAndValidateEmail.
func (mr *MockUsecaseMockRecorder) CreateUserAndValidateEmail(email interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUserAndValidateEmail", reflect.TypeOf((*MockUsecase)(nil).CreateUserAndValidateEmail), email)
}

// ValidateAndExtractToken mocks base method.
func (m *MockUsecase) ValidateAndExtractToken(idToken string) (models.Identity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateAndExtractToken", idToken)
	ret0, _ := ret[0].(models.Identity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidateAndExtractToken indicates an expected call of ValidateAndExtractToken.
func (mr *MockUsecaseMockRecorder) ValidateAndExtractToken(idToken interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateAndExtractToken", reflect.TypeOf((*MockUsecase)(nil).ValidateAndExtractToken), idToken)
}
