// Code generated by MockGen. DO NOT EDIT.
// Source: api/site/interface.go

// Package mock_site is a generated GoMock package.
package mock_site

import (
	gomock "github.com/golang/mock/gomock"
	models "gitlab.odds.team/worklog/api.odds-worklog/models"
	reflect "reflect"
)

// MockRepository is a mock of Repository interface
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// CreateSiteGroup mocks base method
func (m *MockRepository) CreateSiteGroup(site *models.Site) (*models.Site, error) {
	ret := m.ctrl.Call(m, "CreateSiteGroup", site)
	ret0, _ := ret[0].(*models.Site)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSiteGroup indicates an expected call of CreateSiteGroup
func (mr *MockRepositoryMockRecorder) CreateSiteGroup(site interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSiteGroup", reflect.TypeOf((*MockRepository)(nil).CreateSiteGroup), site)
}

// UpdateSiteGroup mocks base method
func (m *MockRepository) UpdateSiteGroup(site *models.Site) (*models.Site, error) {
	ret := m.ctrl.Call(m, "UpdateSiteGroup", site)
	ret0, _ := ret[0].(*models.Site)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateSiteGroup indicates an expected call of UpdateSiteGroup
func (mr *MockRepositoryMockRecorder) UpdateSiteGroup(site interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSiteGroup", reflect.TypeOf((*MockRepository)(nil).UpdateSiteGroup), site)
}

// GetSiteGroup mocks base method
func (m *MockRepository) GetSiteGroup() ([]*models.Site, error) {
	ret := m.ctrl.Call(m, "GetSiteGroup")
	ret0, _ := ret[0].([]*models.Site)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSiteGroup indicates an expected call of GetSiteGroup
func (mr *MockRepositoryMockRecorder) GetSiteGroup() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSiteGroup", reflect.TypeOf((*MockRepository)(nil).GetSiteGroup))
}

// GetSiteGroupByID mocks base method
func (m *MockRepository) GetSiteGroupByID(id string) (*models.Site, error) {
	ret := m.ctrl.Call(m, "GetSiteGroupByID", id)
	ret0, _ := ret[0].(*models.Site)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSiteGroupByID indicates an expected call of GetSiteGroupByID
func (mr *MockRepositoryMockRecorder) GetSiteGroupByID(id interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSiteGroupByID", reflect.TypeOf((*MockRepository)(nil).GetSiteGroupByID), id)
}

// DeleteSiteGroup mocks base method
func (m *MockRepository) DeleteSiteGroup(id string) error {
	ret := m.ctrl.Call(m, "DeleteSiteGroup", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSiteGroup indicates an expected call of DeleteSiteGroup
func (mr *MockRepositoryMockRecorder) DeleteSiteGroup(id interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSiteGroup", reflect.TypeOf((*MockRepository)(nil).DeleteSiteGroup), id)
}

// MockUsecase is a mock of Usecase interface
type MockUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockUsecaseMockRecorder
}

// MockUsecaseMockRecorder is the mock recorder for MockUsecase
type MockUsecaseMockRecorder struct {
	mock *MockUsecase
}

// NewMockUsecase creates a new mock instance
func NewMockUsecase(ctrl *gomock.Controller) *MockUsecase {
	mock := &MockUsecase{ctrl: ctrl}
	mock.recorder = &MockUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockUsecase) EXPECT() *MockUsecaseMockRecorder {
	return m.recorder
}

// CreateSiteGroup mocks base method
func (m_2 *MockUsecase) CreateSiteGroup(m *models.Site) (*models.Site, error) {
	ret := m_2.ctrl.Call(m_2, "CreateSiteGroup", m)
	ret0, _ := ret[0].(*models.Site)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSiteGroup indicates an expected call of CreateSiteGroup
func (mr *MockUsecaseMockRecorder) CreateSiteGroup(m interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSiteGroup", reflect.TypeOf((*MockUsecase)(nil).CreateSiteGroup), m)
}

// UpdateSiteGroup mocks base method
func (m_2 *MockUsecase) UpdateSiteGroup(m *models.Site) (*models.Site, error) {
	ret := m_2.ctrl.Call(m_2, "UpdateSiteGroup", m)
	ret0, _ := ret[0].(*models.Site)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateSiteGroup indicates an expected call of UpdateSiteGroup
func (mr *MockUsecaseMockRecorder) UpdateSiteGroup(m interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSiteGroup", reflect.TypeOf((*MockUsecase)(nil).UpdateSiteGroup), m)
}

// GetSiteGroup mocks base method
func (m *MockUsecase) GetSiteGroup() ([]*models.Site, error) {
	ret := m.ctrl.Call(m, "GetSiteGroup")
	ret0, _ := ret[0].([]*models.Site)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSiteGroup indicates an expected call of GetSiteGroup
func (mr *MockUsecaseMockRecorder) GetSiteGroup() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSiteGroup", reflect.TypeOf((*MockUsecase)(nil).GetSiteGroup))
}

// GetSiteGroupByID mocks base method
func (m *MockUsecase) GetSiteGroupByID(id string) (*models.Site, error) {
	ret := m.ctrl.Call(m, "GetSiteGroupByID", id)
	ret0, _ := ret[0].(*models.Site)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSiteGroupByID indicates an expected call of GetSiteGroupByID
func (mr *MockUsecaseMockRecorder) GetSiteGroupByID(id interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSiteGroupByID", reflect.TypeOf((*MockUsecase)(nil).GetSiteGroupByID), id)
}

// DeleteSiteGroup mocks base method
func (m *MockUsecase) DeleteSiteGroup(id string) error {
	ret := m.ctrl.Call(m, "DeleteSiteGroup", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSiteGroup indicates an expected call of DeleteSiteGroup
func (mr *MockUsecaseMockRecorder) DeleteSiteGroup(id interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSiteGroup", reflect.TypeOf((*MockUsecase)(nil).DeleteSiteGroup), id)
}
